### PR TITLE
Add user avatar to overall_stats

### PR DESCRIPTION
**Pull request by Js41637**
Adds the users avatar to overall_stats, Implements #23 

Don't know if this is the best way either, i've literally never used lxml before a few days ago (or Python for that matter)

**NOTE** I have not tested if this works with this repo, I have my own version of this API that I've remade in Python 2.7 and it works there.

### CODE REVIEW

**Comment by SunDwarf** [comment]
Merged, thanks.

**Comment by Js41637** [comment]
Avatar is still not showing up, not sure if you haven't updated yet or the code doesn't work.

**Comment by SunDwarf** [comment]
Whoops, my cron job updater failed.

All done on the server-side.

**Comment by Js41637** [comment]
Ahh coolio.

**Pull request merged**
