### PR TITLE
Bugfix PlayOverwatch + Tier Image

### PR DESCRIPTION
**Pull request by KingJP**
The PlayOverwatch Website was updated last night. They changed the order of the content boxes so the Games played and other informations can not be parsed.

My current overall stats looks like:

```
    "eu": {
        "stats": {
            "competitive": {
                "overall_stats": {
                    "comprank": 2339,
                    "level": 48,
                    "ties": 0,
                    "rank_image": "https://d1u1mce87gyfbn.cloudfront.net/game/playerlevelrewards/0x0250000000000926_Border.png",
                    "avatar": "https://d1u1mce87gyfbn.cloudfront.net/game/unlocks/0x02500000000008ED.png",
                    "tier": "gold",
                    "wins": 0,
                    "games": 0,
                    "losses": 0,
                    "win_rate": 0,
                    "prestige": 1
                },
```

My Fix also includes the tier image issued in #143 .

### CODE REVIEW

**Comment by Js41637** [comment]
Seems to be true for my profile.

**Comment by Js41637** [comment]
I'm wondering if it might not be better to try to look for the name of the box as the position of the game box is entirely dependent on the amount of stats. It's true in almost all cases it is the last box (5) or 4 if it's missing a group but if you view stats on a hero with very little stats it can be as low as 3.

However i'm also wondering if it's even required to manually find this specific box. I have my own overwatch api that I use for private use but the initial code was based off this however it has changed quite a bit since then but I don't even bother finding the game box and just go over all stats and then look for the `game` stats in those stats which kinda works around this issue?

**Comment by SunDwarf** [comment]
I looked at this earlier, set a mental note to check it out later, then didn't. Anyway I was having a nice dream, where I was like, successful and some shit, then I got woken up by this annoying thing. You know how sometimes in a dream, you're walking then you trip and jolt awake? I got awoken by that. And it was really fucking annoying because the dream was really good, then I woke up and was really sad because I was back to my regular shit life in reality.

Anyway, after that I woke up and checked my tablet, and this had another comment, so I decided to get out of bed and decided to see if I should merge this. 

Have you tested it with a bunch of different battletags, including edge case ones? Because I sure as shit won't, and whilst I merge breaking changes into production constantly, I thought maybe I might be nice to my end users and actually see if this works.

Given that this changes an arbitrary index, I'm like 90% certain given blizzard shit HTML that this breaks some account without specific stats. And 500 errors give me a mean Sentry alert now, which I usually ignore because it's shitty clients disconnecting before I can send data, but they still pop up.

**Comment by SunDwarf** [comment]
Also I'm rewriting the API code, coming soon to a store near you in 2018, and rewriting the parser to be less abysmal. Just a heads up.

**Comment by Js41637** [comment]
You can view my shitty code. I only made it a certain way to suit my needs but Blizzard have basically completely fucked everything and I can no longer get what I want with averages and such but it was a neat learning experience. Also rewrite it because I needed to run on Python 2.7
https://github.com/Js41637/Overwatch-API/blob/master/src/parsers.py

**Comment by SunDwarf** [comment]
I'll probably write a full, from-scratch parser that's much more modular and easily fixable than magic numbers and magic xpaths all over the place instead.

**Comment by Js41637** [comment]
Yeah probably better, I only used python because I copied this api and was too lazy to write one from scratch in node. Also Google App Engine didn't support node at the time and it can run the python 2.7 version for freeeeeeeeee

**Comment by mdotk** [comment]
I don't think the changes in this request fix the issue

**Comment by Js41637** [comment]
Your issues overall_stats not being added? This change is directly related to how the api detects overall_stats?

**Comment by mdotk** [comment]
Yes, 0 for many of the "overall_stats" are still returned even with the changes made by this request

**Comment by KingJP** [comment]
When I woke up this morning I checked my phone and had about 20 E-Mails from GitHub. Thank You for replying on this request and rewriting the API! It makes me sad that I can not participate in the discussions because I live in Germany. We always have a time delay in writing answers.

@mdotk Can you provide some examples where values in "overall_stats" are 0?
I tested the Fix using 100 different BattleTags from EU Stats. Maybe US Stats are different?

**Comment by mdotk** [comment]
@KingJP I've reverted the changes on my server, but for example try Txao-21793 on PC. I made the changes in this request and ran the API. overall_stats still came back as 0

**Comment by KingJP** [comment]
I think it's kinda "works on my machine" thing. I called the API for user "Txao-21793" on my server and got the following result for "us", "kr" and "eu". 

```
{
    "eu": {
        "stats": {
            "competitive": {
                "overall_stats": {
                    "wins": 43,
                    "rank_image": "https://d1u1mce87gyfbn.cloudfront.net/game/playerlevelrewards/0x0250000000000967_Border.png",
                    "prestige": 7,
                    "ties": 0,
                    "level": 20,
                    "comprank": 4596,
                    "losses": 23,
                    "avatar": "https://d1u1mce87gyfbn.cloudfront.net/game/unlocks/0x0250000000000D69.png",
                    "tier_image": "https://d1u1mce87gyfbn.cloudfront.net/game/rank-icons/season-2/rank-7.png",
                    "games": 66,
                    "win_rate": 65.15,
                    "tier": "grandmaster"
                }
```

Please notice that there is a difference to the Quickplay "overall_stats". They only return the Quickplay values they can gather on playoverwatch like "Wins" or "Level".

Quickplay stats look like:

```
{
    "eu": {
        "stats": {
            "quickplay": {
                "overall_stats": {
                    "win_rate": 0,
                    "losses": 0,
                    "rank_image": "https://d1u1mce87gyfbn.cloudfront.net/game/playerlevelrewards/0x0250000000000967_Border.png",
                    "prestige": 7,
                    "tier_image": "https://d1u1mce87gyfbn.cloudfront.net/game/rank-icons/season-2/rank-7.png",
                    "avatar": "https://d1u1mce87gyfbn.cloudfront.net/game/unlocks/0x0250000000000D69.png",
                    "wins": 884,
                    "level": 20,
                    "tier": "grandmaster",
                    "games": 0,
                    "comprank": 4596
                }
```

Maybe you should disable caching for your tests after changing the code. Maybe the result you got was cached by redis-server.

**Comment by mdotk** [comment]
@KingJP just confirming it does indeed fix the issue. Sorry for the false report. I had to restart OWAPI

**Comment by SunDwarf** [comment]
Put into production. Let's hope nothing explodes.

**Pull request merged**
