### PR TITLE
Rework avg stats to follow same format as general/overall_stats

### PR DESCRIPTION
**Pull request by azah**
I commented out Rank from overall stats since it just returns Null always. If Blizz adds a rank or something then it should be uncommented.

---

I reworked the average stats, because the data structuring was different from the rest of the API.
Here is a sample output:
```json
{
    "battletag": "Dad-12262",
    "average_stats": {
        "objective_time_avg": 0.01611111111111111,
        "damage_done_avg": 9858.0,
        "defensive_assists_avg": 1.0,
        "melee_final_blows_avg": 0.29,
        "time_spent_on_fire_avg": 0.0275,
        "objective_kills_avg": 8.06,
        "healing_done_avg": 1932.0,
        "final_blows_avg": 11.4,
        "offensive_assists_avg": 0.0,
        "deaths_avg": 10.59,
        "solo_kills_avg": 3.56,
        "eliminations_avg": 21.22
    },
    "game_stats": {
        "eliminations_most_in_game": 60.0,
        "final_blows": 502.0,
        "defensive_assists_most_in_game": 17.0,
        "time_played": 9.0,
        "solo_kills_most_in_game": 29.0,
        "medals_bronze": 37.0,
        "objective_kills_most_in_game": 26.0,
        "objective_time": 0.7133333333333333,
        "damage_done_most_in_game": 25730.0,
        "multikill_best": 5.0,
        "games_played": 44.0,
        "time_spent_on_fire_most_in_game": 0.10888888888888888,
        "defensive_assists": 65.0,
        "melee_final_blows": 13.0,
        "offensive_assists_most_in_game": 4.0,
        "offensive_assists": 17.0,
        "kpd": 2.0,
        "eliminations": 934.0,
        "healing_done": 84987.0,
        "objective_kills": 355.0,
        "solo_kills": 157.0,
        "time_spent_on_fire": 1.2125,
        "damage_done": 433736.0,
        "final_blows_most_in_game": 29.0,
        "medals_silver": 36.0,
        "environmental_deaths": 15.0,
        "melee_final_blows_most_in_game": 3.0,
        "cards": 13.0,
        "games_won": 21.0,
        "healing_done_most_in_game": 9881.0,
        "multikills": 19.0,
        "medals": 110.0,
        "deaths": 466.0,
        "medals_gold": 37.0,
        "objective_time_most_in_game": 0.07638888888888888,
        "environmental_kills": 8.0
    },
    "_request": {
        "route": "/api/v2/u/Dad-12262/stats/competitive",
        "api_ver": 1
    },
    "overall_stats": {
        "win_rate": 47,
        "level": 96,
        "games": 44,
        "prestige": 0,
        "comprank": 46,
        "wins": 21,
        "losses": 23
    },
    "region": "us"
}
```

It may be tautological to keep _avg on the end of the average stats, but I think it enhances readability down the line.

---

I also added some more 0x IDs to the PRESTIGE dictionary. 
We need 10 per prestige (and non-prestige). Since the borders look different as you level up.

The easiest way to do this would be to go to MasterOverwatch & sort by Level. The issue being actually finding profiles in each level bracket.

### CODE REVIEW

**Comment by azah** [comment]
Should I implement #23?
#25 or #22 should be reopened until we get all the IDs up to P5.

**Comment by SunDwarf** [comment]
I agree; I merged the last one because honestly I didn't know how to add averages and just wanted one in.

If you want to add #23, it should go in a separate PR, of course.

I've re-opened #25 for now.

Thanks for your work!

**Comment by azah** [comment]
Np. What I'm saying though is you do think it's worth it to get user avatar urls? Not sure how useful it would be.

**Comment by SunDwarf** [comment]
The more data the better!

**Comment by Jack97** [comment]
@azah if you could find the time to implement a way to get user avatar url's that would be great :)

**Comment by Js41637** [comment]
See #30

**Pull request merged**
