### PR TITLE
Added competitive stats endpoint

### PR DESCRIPTION
**Pull request by Downy**
Returns competitive stats in the same format as regular quickplay stats.
Edit; poorly worded.

### CODE REVIEW

**Comment by SunDwarf** [comment]
Maybe I'm missing something, but I don't see how this returns different data?

**Comment by Downy** [comment]
Haha, I can definitely see why. It's literally a one-digit change.

parsed.xpath(".//div[@data-group-id='stats' and @data-category-id='0x02E00000FFFFFFFF']")[0] (your code)
parsed.xpath(".//div[@data-group-id='stats' and @data-category-id='0x02E00000FFFFFFFF']")[1] (my code)

Both competitive and quickplay use the same id's, so the competitive stats are [1] in the array, whereas quickplay is [0].

**Comment by SunDwarf** [comment]
Ohh. Alright, I'll merge with a handful of changes.

**Comment by SunDwarf** [comment]
Alright, I made a breaking change as a redirect.

Good HTTP libs should handle this.

**Pull request merged**
